development:
  adapter: postgresql
  encoding: unicode
  database: mtp_development
  pool: 5
  username: neilmarion
  password: root

test:
  adapter: postgresql
  encoding: unicode
  database: mtp_test
  pool: 5
  username: neilmarion
  password: root
