# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

puts "Creating Organizations"

a = Organization.create(name: 'ROOT', type_of_children: 'ROOT')
a = inc = a.children.create(name: 'IGLESIA NI CRISTO', type_of_children: 'District', longitude: "121.0653943", latitude: "14.6632838")
a = a.children.create(name: 'Metro Manila South', type_of_children: 'Locale', longitude: "121.0107383", latitude: "14.5469972")
a = talon_org = a.children.create(name: 'Talon', type_of_children: 'Purok', longitude: "14.445282806398495", latitude: "120.98913688280334")

puts "Creating Purok suborganizations for #{talon_org.name}"

for i in 1..4 
  a.children.create(name: i.to_s, type_of_children: 'Grupo') 
end

puts "Creating Grupo suborganizations for #{talon_org.name} Puroks"

a.children.each do |c|
  for i in 1..10
    c.children.create(name: i.to_s)
  end
end

if Office.all.empty?
  Office.create(name: 'Pastor')
  Office.create(name: 'Manggagawa')
  temp = Office.create(name: 'Pangulong Diakono')
    temp.children.create(name: 'PD-1')
    temp.children.create(name: 'PD-2')
    temp.children.create(name: 'PD-3')
    temp.children.create(name: 'PD-4')
    temp.children.create(name: 'PD-5')
  Office.create(name: 'Pagkadiakono/nesa')
  temp = Office.create(name: 'Pagkakatiwala')
    temp.children.create(name: 'Katiwala ng Purok')
    temp.children.create(name: 'II Katiwala ng Purok')
    temp.children.create(name: 'Katiwala ng Grupo')
    temp.children.create(name: 'II Katiwala ng Grupo')
  temp = Office.create(name: 'Mangaawit')
    temp.children.create(name: 'Kabataan')
    temp = temp.children.create(name: 'Katandaan')
      temp.children.create(name: 'Soprano')
      temp.children.create(name: 'Alto')
      temp.children.create(name: 'Tenor')
      choir_adult_bass = temp.children.create(name: 'Bass')
  temp = Office.create(name: 'Kalihiman')
    temp.children.create(name: 'Pangulo')
    temp.children.create(name: 'II Pangulo')
    temp.children.create(name: 'Kalihim')
  temp = Office.create(name: 'Pananalapi')
    temp.children.create(name: 'P-1')
    temp.children.create(name: 'P-9')
    temp.children.create(name: 'P-13')
  cfo = Office.create(name: 'Kapisanan/CFO')
    buklod = cfo.children.create(name: 'Buklod')
      buklod.children.create(name: 'Pangulo')
      buklod.children.create(name: 'II Pangulo')
      buklod.children.create(name: 'Kalihim')
      scac = buklod.children.create(name: 'SCAC')
        scac.children.create(name: 'Chairperson')
        scac.children.create(name: 'Vice Chairperson')
        scac.children.create(name: 'Kagawad')
      sdsc = buklod.children.create(name: 'SDSC')
        sdsc.children.create(name: 'Chairperson')
        sdsc.children.create(name: 'Vice Chairperson')
        sdsc.children.create(name: 'Kagawad')
      cfec = buklod.children.create(name: 'CFEC')
        cfec.children.create(name: 'Chairperson')
        cfec.children.create(name: 'Vice Chairperson')
        cfec.children.create(name: 'Kagawad')
      purok = buklod.children.create(name: 'Purok')
        purok.children.create(name: 'Purok Leader')
        purok.children.create(name: 'II Purok Leader')
        purok.children.create(name: 'Kalihim')
        purok.children.create(name: 'Kagawad')
    kadiwa = cfo.children.create(name: 'Kadiwa')
      kadiwa.children.create(name: 'Pangulo')
      kadiwa_ii_pangulo = kadiwa.children.create(name: 'II Pangulo')
      kadiwa.children.create(name: 'Kalihim')
      scac = kadiwa.children.create(name: 'SCAC')
        scac.children.create(name: 'Chairperson')
        scac.children.create(name: 'Vice Chairperson')
        scac.children.create(name: 'Kagawad')
      sdsc = kadiwa.children.create(name: 'SDSC')
        sdsc.children.create(name: 'Chairperson')
        sdsc.children.create(name: 'Vice Chairperson')
        sdsc.children.create(name: 'Kagawad')
      cfec = kadiwa.children.create(name: 'CFEC')
        cfec.children.create(name: 'Chairperson')
        cfec.children.create(name: 'Vice Chairperson')
        cfec.children.create(name: 'Kagawad')
      purok = kadiwa.children.create(name: 'Purok')
        purok.children.create(name: 'Purok Leader')
        purok.children.create(name: 'II Purok Leader')
        purok.children.create(name: 'Kalihim')
        purok.children.create(name: 'Kagawad')
    binhi = cfo.children.create(name: 'Binhi')
      binhi.children.create(name: 'Pangulo')
      binhi.children.create(name: 'II Pangulo')
      binhi.children.create(name: 'Kalihim')
      scac = binhi.children.create(name: 'SCAC')
        scac.children.create(name: 'Chairperson')
        scac.children.create(name: 'Vice Chairperson')
        scac.children.create(name: 'Kagawad')
      sdsc = binhi.children.create(name: 'SDSC')
        sdsc.children.create(name: 'Chairperson')
        sdsc.children.create(name: 'Vice Chairperson')
        sdsc.children.create(name: 'Kagawad')
      cfec = binhi.children.create(name: 'CFEC')
        cfec.children.create(name: 'Chairperson')
        cfec.children.create(name: 'Vice Chairperson')
        cfec.children.create(name: 'Kagawad')
      purok = binhi.children.create(name: 'Purok')
        purok.children.create(name: 'Purok Leader')
        purok.children.create(name: 'II Purok Leader')
        purok.children.create(name: 'Kalihim')
        purok.children.create(name: 'Kagawad')
  scan = Office.create(name: 'SCAN')
    scan.children.create(name: 'Pangulo')
    scan.children.create(name: 'II Pangulo')
    scan.children.create(name: 'Kalihim')
    scan.children.create(name: 'SCAN')
  pnk = Office.create(name: 'PNK')
    pnk.children.create(name: 'Pangulo ng Lupon')
    pnk.children.create(name: 'Guro')
    pnk.children.create(name: 'Pangulo ng Dako')
    pnk.children.create(name: 'II Pangulo ng Dako')
    pnk.children.create(name: 'Kalihim ng Dako')
    pnk.children.create(name: 'II Kalihim ng Dako')
    pnk.children.create(name: 'Ingat Yaman')
    pnk.children.create(name: 'II Ingat Yaman')
    pnk.children.create(name: 'Tagasuri')
    pnk.children.create(name: 'II Tagasuri')
    pnk.children.create(name: 'Kagawad')
  Office.create(name: 'Gardener')
end

if Cfo.all.empty?
  Cfo.create(name: 'Buklod')
  kadiwa = Cfo.create(name: 'KaDiWa')
  Cfo.create(name: 'Binhi')
end

person = Person.create(last_name: "dela Cruz", first_name: "Neil Marion", middle_name: "Flores", organization_id: talon_org.id, cfo_id: kadiwa.id)
person.addresses.create(address: "05B Avocado St., Verdant Acres Subd., Pamplona 3, Las Pinas City", latitude: "14.4557085", longitude: "120.9824231")

person.offices = [choir_adult_bass, kadiwa_ii_pangulo]

User.create({email: "nmfdelacruz@gmail.com", password: "eloisa", password_confirmation: "eloisa", organization_id: inc.id})
User.create({email: "joepagz@finder.com", password: "talon", password_confirmation: "talon", organization_id: inc.id})
User.create({email: "talon_user@finder.com", password: "jose", password_confirmation: "jose", organization_id: talon_org.id})
